//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.13 at 05:47:39 AM MSK 
//


package org.w3._2001.xmlschema;

import javax.xml.bind.annotation.*;


/**
 * 
 *       for maxOccurs
 * 
 * <p>Java class for allNNI simple type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;simpleType name="allNNI">
 *   &lt;union memberTypes=" {http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
 *     &lt;simpleType>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *         &lt;enumeration value="unbounded"/>
 *       &lt;/restriction>
 *     &lt;/simpleType>
 *   &lt;/union>
 * &lt;/simpleType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "allNNI", propOrder = {
    "value"
})
public class AllNNI {

    @XmlValue
    @XmlSchemaType(name = "allNNI")
    protected String value;

    /**
     * 
     *       for maxOccurs
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

}
